### ISSUE TITLE
Footer breakpoints look weird when resizing the window

### ISSUE THREAD

**Issue by agjmills** [freenode/web-7.0#129]
![screen shot 2016-03-23 at 12 24 32](https://cloud.githubusercontent.com/assets/1158289/13985069/4a0eb234-f0f2-11e5-9350-ce5de59c488e.png)

**Comment by edk0** [comment]
"Social Media" forces itself to the right deliberately—it seemed weirder when it jumped over to the left.

Do you think it'd look better if Groups always sat on the bottom row?

**Comment by tinyhippw** [comment]
Yeah, I think it's more natural to split from a 1x4 row to a 2x2 rows then to a 4x1 row

**Comment by svbeon** [comment]
@tinyhippw that approach would definitely look good

**Comment by mission712** [comment]
I'm going to work on this and see if it works.
