### ISSUE TITLE
Breadcrumbs for a11y

### ISSUE THREAD

**Issue by tinyhippw** [freenode/web-7.0#130]
I think it would be good for the website to have some level of breadcrumbs to work out where you are, and to quickly get back to the page you were just on, other than hitting the back button

**Comment by svbeon** [comment]
Eventually this could be a good idea... I'm not a big fan of breadcrumbs tough especially as they seem to be on every single YABSS... But for pagespages that have a depth I could see the point of it

**Comment by edk0** [comment]
Closing for now, in favour of #140
