### ISSUE TITLE
Social icons disproportionally large for small viewports

### ISSUE THREAD

**Issue by tinyhippw** [freenode/web-7.0#131]
![screen shot 2016-03-23 at 15 10 36](https://cloud.githubusercontent.com/assets/1158289/13989689/78a89bd4-f109-11e5-9397-2009680711b2.png)

**Comment by edk0** [comment]
that's deliberate, fwiw (changed in 7e59dd2d01bcda58a796cb111aa7c51d8a070ca8); the big icons i think were supposed to make things easier to click on mobile and stuff.

without that change: https://freenode.net/web-7.0/revert-big-icons/

**Comment by svbeon** [comment]
Yes, it's intended to
  - a) make it easier to click on small screens
  - b) save space

**Comment by svbeon** [comment]
Eventually they shouldn't activate until an even smaller screen size...
