### ISSUE TITLE
UX: Most important information is well hidden

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#134]
One of the most important information for an IRC network is how to connect, thus: server address(es) and port(s).  This information is well hidden on the new website, I recommend either placing it on the front page or at least linking it.

**Comment by svbeon** [comment]
I think the .box "Chat" should be relinked to /kb/connect to solve this where chat.fn.net is linked. Also we should eventually  make that c.fn.net into an  link `[c.fn.n](irc://chat.freenode.net:6667)`

**Comment by Fuchs** [comment]
That's one way, what I suggest is maybe putting

"connect via an IRC client:"
<a href="irc://chat.freenode.net:6697/freenode ">chat.freenode.net:6697</a> <a href="irc://chat.freenode.net:6667/freenode"Non-SSL: 6667</a>

Somewhere prominently enough (footer?) 
So you'd have both the most important connection information  (address and standard ports for SSL and non-SSL) plus it is clickable for the lazy  (while not a standard, quite a lot of browsers, operating systems and IRC client chains these days can handle irc: chatlinks)

**Comment by svbeon** [comment]
Yes that sounds like a good idea to me, feel free to PR

**Comment by Fuchs** [comment]
For reasons explained on IRC I'm afraid I won't be able to contribute code directly, I kindly ask one of the devs to do so. Thanks for your understanding and feedback.

**Comment by Fuchs** [comment]
Imo not resolved yet, you covered one part  (a clickable IRC link), but now the information is not available in written form for those who don't have irc:/  in their browser/OS/client, thus my initial suggestion of writing it out in the <a> text.

**Comment by edk0** [comment]
Reasonable point. I don't really think the footer has room for that, though, so it'll take some more thinking about.

**Comment by Fuchs** [comment]
I think width-wise my solution is not wider than other text, if you split it up to two lines  (that was intended, unfortunately GitHub issue formatting is a bit bleh, so maybe it didn't come across as that). You'd only have one line more than currently, but given the current footer height I'd say that is manageable. 

So:  
Connect via an IRC client <newline>
<link here> <non SSL here>

Alternative is to have a one line link (the above) going to a page giving out details, in my opinion however connect information should be front-page  (staff might disagree, so the link-to-page solution would be a good alternative)
