### ISSUE TITLE
UX: Lack of anchors for linking

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#135]
As discussed on IRC, if multiple pieces of information  (e.g. registering a nick, identifying to it and nick expiration) are kept on the same page, for the sake of linking to it  (either from project documentation, IRC or whatever else) it would be nice to have anchors. 

A different approach would be having separate pages for that kind of information, from an UX point of view I highly discourage that as some information depends on other information or, based on context, can be part of a workflow.

**Comment by svbeon** [comment]
a) point is to have the pages splitter and interlink them a lot
b) anchors where left out on purpose (decided by @christeld)

**Comment by edk0** [comment]
This was indeed deliberate, closing

**Comment by Fuchs** [comment]
As on IRC it was mentioned that GitHub issues would be a good place to discuss that kind of thing, I am a bit sad with a  one liner  "closed, won't fix" approach.

What are the arguments against having anchors? I yet have to see a downside, but it would be nice to have them if needed, so that projects and people can link to specific content if needed.

**Comment by edk0** [comment]
the argument was mentioned in IRC—interacting with people is supposed to be preferred over just linking them to a web page.

sorry if I was too quick to close this; I got the impression freenode's position on this issue was pretty definite.

**Comment by Fuchs** [comment]
It's fine if freenode's position is that, but keep in mind that projects using freenode have documentation  (among them: arch linux and ubuntu linux who both have a wiki including IRC specific things), and those either have to link to the website or have an own copy of the content. Having an own copy is highly discouraged because such information can be outdated and thus updating it on the main source is either undetected or has to be re-done all over the places who copy it. 

If freenode prefers to have the same content repeated in #freenode or query for the sake of user interaction that's understandable and fine, but given that freenode provides services for the FOSS community, I'd also keep them in mind when making such decisions, they might have different policies. And for those: anchors would help, while they don't have any downside.

**Comment by Mikaela** [comment]
> the argument was mentioned in IRC—interacting with people is supposed to be preferred over just linking them to a web page.

Doesn't this mean that people just link to the page and say "read this" and people have to read it entirely as they cannot be linked to the specific point of what they are looking for?

**Comment by mistohise** [comment]
Probably. It may be that we are looking for a technical "solution" to a non-technical problem. (I.E. that removing anchors can't prevent lazy people from wanting to send people to a web page)

**Comment by Fuchs** [comment]
I don't think that using technical solutions for solving people problems will help. 

I can see two things happening: people will either link to the old site which had anchors  (and thus potentially giving out outdated information) or, worse, create copies of their own, as it has been done in the past with the gists and the likes. So you not only don't gain anything  (people will still throw URLs at people instead of interacting with them), but you also have potentially outdated or wrong information being thrown around.

**Comment by mistohise** [comment]
Yes, I suspect that @Fuchs is correct, despite what we might want to see out of removing anchors.

**Comment by edk0** [comment]
In this case I think we should consider pulling out anchor-worthy content into other pages where that makes sense. Big pages full of lots of sections are confusing and place significance on the order of entries (there's not necessarily a good one). We can solve the problem of flowing to related information with directed "see also"-type links where they're appropriate.

**Comment by Fuchs** [comment]
That works, however, depending on your hierarchy I then either suggest a search box (flat) or https://github.com/freenode/web-7.0/issues/130 (if deep / tree like).  In case of workflows: yes, see also or, in case of step by step stuff, next and previous.

**Comment by mistohise** [comment]
Nothing should be long enough to warrant a search box. If we end up with pages that are that long then we've completely failed one of the key design elements for the new site.

**Comment by Fuchs** [comment]
A cross page search box on the home page, if you spread information over many small sub pages. In-page searching all decent browsers can do out of the box.

**Comment by mistohise** [comment]
Oh I see what you mean. Yeah probably.

**Comment by Fuchs** [comment]
Could these be re-added in the meantime? 

Apparently it's no longer discouraged to use them (in addition to the arguments about external projects), seeing

*** The channel topic is "Welcome to #freenode | Feel free to message staff at any time. You can find us using /stats p (shows immediately-available staff) or /who freenode/staff/* (shows all staff) | https://freenode.net/kb/answer/cloaks#cloaks-do-not-effectively-hide-your-ip".

**Comment by svbeon** [comment]
I mean, the anchors are there... Just not explicitly visible... I could look into adding a small link to here `<a>` after/before headers if you think that's a good way to make them more visible?

**Comment by Fuchs** [comment]
Titles that contain spaces (and other) are hard to anchor because the user has no idea what the anchor would be called  (just copy&pasting the title does not work, I tried that when a user asked about linking to off-topic earlier today in #freenode, which is what brought this up again)

**Comment by svbeon** [comment]
I'll add it to my todo then

**Comment by Fuchs** [comment]
Apparently not so trivial as cms7 just uses pythons markdown for most of the work, but we already use the ToC extension, which can be configured to add anchors to links. A simple 

```
diff —git a/cms7/source.py b/cms7/source.py
index 88f26fd..e1e418b 100644
—- a/cms7/source.py
+++ b/cms7/source.py
@@ -43,7 +43,7 @@ class MarkdownSource:
                 TableExtension(),
                 WikiLinkExtension(),
                 CMS7Extension(gs, path=self.source, baselevel=baselevel, hyphenate=hyphenate, paragraphs=paragraphs),
-                TocExtension()
+                TocExtension(anchorlink=True)
```

would do, but this would require 

1) testing if this doesn't add it in super odd places
2) if 1), see if that can be changed / overridden / configured
3) potentially some css to make it look not-ugly
