### ISSUE TITLE
News archive is horribly styled

### ISSUE THREAD

**Issue by edk0** [freenode/web-7.0#137]

**Comment by svbeon** [comment]
Duplicate of #126

**Comment by svbeon** [comment]
The header margins looks horrible on small screens, 
![screenshot_2016-03-24-18-13-33](https://cloud.githubusercontent.com/assets/10356719/14025071/7fef57c8-f1ec-11e5-9086-5f57c44f6c02.png)

**Comment by edk0** [comment]
Not related to small screens
