### ISSUE TITLE
Design: waste of horizontal space

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#138]
On desktop resolutions, pages which are mostly text  (e.g. http://freenode.net/changuide) have a lot of horizontal whitespace. 

These days most desktop screens have a wide screen format, thus going for vertical space instead of horizontal space makes less information visible and requires scrolling.  Also this requires the visual point of focus to jump a lot while reading, which makes the text more tiresome to read.

**Comment by svbeon** [comment]
We've considered a lot of widths and come to a conclusion that this width is the best to consume.

(If your fingers hurt from scrolling I would recommend some kind of working out ;))

**Comment by edk0** [comment]
Personally, if the text's any wider I start finding it tiring to scan it.

I do think if we keep the text this width we should waste a bit more vertical space though (seriously) to prevent pages with very short content looking so odd.

**Comment by Ttech** [comment]
The alternative to this is not using wide interface items on a narrow site, generally they recommend using the wide navigation and have the content box the same size as the designed width. (GitHub does this)

**Comment by boxmein** [comment]
http://baymard.com/blog/line-length-readability

http://ux.stackexchange.com/questions/3618/ideal-column-width-for-paragraphs-online

http://webstyleguide.com/wsg3/7-page-design/6-page-width-line-length.html

Consider these before trying to fill up the page with information. Information density is way less relevant than ease of reading in a *blog*. This isn't a monitoring dashboard meant for internal use, this is a public-facing blog aimed to attract readers.

**Comment by Ttech** [comment]
Part of the issue I think is that there's no breadcrumbs for some of the ui and the main navigation is stuck on the bottom as well.

**Comment by Fuchs** [comment]
Breadcrumbs only make sense if you have some depth, currently the hierarchy is rather flat, so I don't think breadcrumbs would do much. 
If sub-categories or the likes are implemented, breadcrumbs could help.

**Comment by tinyhippw** [comment]
We discussed this in -website, and there was #116 which was partly reverted by #120 as we decided the text width was pretty much the best balance between readability and use-of-space.

Also discussed breadcrumbs, and agreed that we need them in a number of places, I'll add another issue later for that.

**Comment by Fuchs** [comment]
Closed due to lots of seductive talking on mumble
