### ISSUE TITLE
SASL configuration information lacking

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#139]
A quite important piece of information, how to connect via SASL, has not been ported from the old website. 

This is especially bad because

1) The content was already there and correct
2) Users of some ISPs and VPN providers  are required to connect via SASL, thus for these users this is vital information

**Comment by nhandler** [comment]
Also noting here that we have a broken link on http://freenode.net/kb/answer/registration pointing to http://freenode.net/kb/answer/registration#XXXkb/using/sasl

**Comment by tinyhippw** [comment]
added SASL docs in #203 

But the KB now looks... shit... need to work out some kind of hierarchy, please discuss in #203!
