### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#140]
In case of information being spread over lots of separate pages: maybe add a search box (header)
(floating left to PIA logo) 

(This comment has been heavily edited by the repository owner without my consent and thus no longer necessarily represents my views and opinions)

**Comment by svbeon** [comment]
2 and 3 should be discussed under their own issues, a search box could be useful but I wouldn't place it in the header (as to keep that one clean) I would prefer below the .jumbotron or inside .footer

**Comment by svbeon** [comment]
Reference #141
