### ISSUE TITLE
Suggestion: re-linking

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#143]
As soon as it is clear where content is placed (e.g. sub-pages or one big page, but with anchors): 

It would be great if for information that was present on the old page and is still available on the new one (Examples: SASL, Nick registration, On- and Off-Topic, Channel Guidelines, Nick Expiry, Connecting to freenode) some re-linking could be set up. 

Reason: lots of projects have these links in their internal documentation  (Wiki, written documentation, IRC bots and topics ...) which are now all dead, despite the content still being there.

**Comment by svbeon** [comment]
I'm not sure if this is possible using github pages, ideally we would have set up a bunch of 302's I say...

**Comment by svbeon** [comment]
Connected to this is partly if we can get cloudflare to use the 404 page we have instead of the cloudflare one ( @christeld )

**Comment by mistohise** [comment]
I generally disagree with the idea of forwarding from the old information to new stuff. I'd rather have a generic 404 or push back to the front page. There's no point redesigning the entire site and then having people access stuff via outdated routes.

**Comment by svbeon** [comment]
Compromise done with #318 and #325
