### ISSUE TITLE
Site is inaccessible or severely degraded over SSL

### ISSUE THREAD

**Issue by Mikaela** [freenode/web-7.0#149]
Tapping CTRL + F5 changes nothing.

![Chromium](https://i.imgur.com/vQD5ysG.png)

![Google Chrome](https://i.imgur.com/u24VsJS.png)

**Comment by edk0** [comment]
I've been getting this too (intermittently); as far as I can tell it's a cloudflare problem.

**Comment by Mikaela** [comment]
[CloudFlare status](https://www.cloudflarestatus.com/) seems to be claiming *All Systems Operational*.

**Comment by Mikaela** [comment]
It seems that going to other pages than freenode.net throws:

> Error 522 Ray ID: 28897c62fdb53798 • 2016-03-24 10:37:22 UTC
Connection timed out

so apparently freenode.net is cached and your host is down or has some other issue.

**Comment by edk0** [comment]
For clarification - I mean that there's something wrong with the cloudflare setup. The underlying origin server is github pages, which is working fine, but cloudflare can't access it (only for SSL connections, it seems).

**Comment by Mikaela** [comment]
What kind of settings do you have there currently? If I had to guess, I would say that you are currently using something else than "flexible SSL" [CloudFlare support](https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-Off-Flexible-SSL-Full-SSL-Full-SSL-Strict-SSL-Only-mean-) which is the only one that can be used with GitHub pages custom domain.

![helpful image from CloudFlare](https://support.cloudflare.com/hc/en-us/article_attachments/200258600/cf_ssl_settings.png)

**Comment by edk0** [comment]
I believe (I can't see the settings) we are using flexible SSL. I think spb recently fixed something though; are you still getting errors?

**Comment by Mikaela** [comment]
It seems to be working again.
