### ISSUE TITLE
Content: Lack of channel mode help

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#153]
The old page provided help on cmodes, this has not been ported (yet) to the new page. 

This is bad as the official documentation of the ircd (/help cmodes) lacks modes (e.g. +S for SSL only) or important parameters, e.g. the extban syntax, which is both important for +b but also for +I, which had great examples on the old page that are now lacking.

**Comment by tinyhippw** [comment]
Happy to receive contributions for content - if anyone spots some good copy already explaining this, I'd be interested in using that as a basis for this KB article

**Comment by Fuchs** [comment]
http://web.archive.org/web/20160212092427/https://www.freenode.net/using_the_network.shtml   "User and channel modes". As far as I can see, all of that is up to date and correct.

**Comment by tinyhippw** [comment]
Awesome, now just to find someone that wants to port it into the KB format :)

**Comment by babilen** [comment]
The old "using the network" article was *very* useful and it appears to have been removed from the current website along with other pages (such as the one on CertFP, which is now a dead link from https://freenode.net/kb/answer/chat to https://freenode.net/kb/answer/chat#XXX).

I have been informed that some useful information can be retrieved with the `/quote help cmode` or `/quote help umode` commands that also don't appear to be documented elsewhere. It would really be appreciated if you could bring back the old content as it made using freenode a lot easier.

**Comment by Fuchs** [comment]
Closed with https://github.com/freenode/web-7.0/pull/241

**Comment by babilen** [comment]
Thank you!
