### ISSUE TITLE
Some pages use incorrect markup for headings

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#163]
Currently paragraph headings  (e.g. "Nickname ownership" on http://freenode.net/policies) are just bolded paragraphs, which results in no vertical spacing. Pages with lots of paragraphs with a heading (e.g.  http://freenode.net/policies) appear vertically as one single block of text. 

Either add some vertical spacing (more top than bottom), or convert them to html headings.

**Comment by edk0** [comment]
We do have real headings (see https://freenode.net/support for example), but for some reason not all the articles use them, so I'm recategorizing this as a content issue
