### ISSUE TITLE
Cloudflare cache and SRI

### ISSUE THREAD

**Issue by svbeon** [freenode/web-7.0#171]
Eventually implement an addition to Subresources to be updated by cloudflare by letting cms7 add ?commit to the end of the link, for example:
```html
<link href="static/css/style.css?8e4058c" rel="stylesheet"/>
```

Also eventually let cms7 calculate the css files SRI hashes and add them, for example:
```html
<link href="static/css/style.css" rel="stylesheet" integrity="sha384-az4KLkHdzQqenZ5ZMjJQPXpywcnHbBuaxVUbO/ZOk5WdI3uslVMOm4lA2b5GhDv9" crossorigin="anonymous"/>
```

**Comment by edk0** [comment]
Do we need SRI? It's not that hard to implement (in fact I've already done it) but, given that we host all our own styles anyway, we don't have the problem that SRI was designed to solve.

**Comment by svbeon** [comment]
Yeah I know, we don't really need it but I just bought it up as it gives an extra layer of security (and some extra points on httpsecurityreport)

**Comment by edk0** [comment]
I'm pushing the git hashes but not SRI for now. I'm not convinced it shouldn't say that way; remember that all features add complexity.

**Comment by svbeon** [comment]
Well my only point of throwing out this random idea (SRI) that's for ext resources mainly, and not a big problem to us as we don't use js (wich I see as a worse problem if they are edited... You can't add HTML via css, but text tough) was if someone else in the future was going to use cms7, I'll leave this open for someone else to close, but I'm fine with closing it when ?commit is pushed.

**Comment by edk0** [comment]
Acknowledged; I'll close this and revisit the issue if somebody needs it
