### ISSUE TITLE
Old links in news posts

### ISSUE THREAD

**Issue by svbeon** [freenode/web-7.0#186]
See [this paste](http://pastebin.com/jSnhyAAw) that contains a grep output of `grep -r "shtml" content` on branch master, eventually some of those links should be edited

**Comment by mistohise** [comment]
yeah that's annoying.

**Comment by mistohise** [comment]
They probably don't get much clickthrough, though.

**Comment by christeld** [comment]
I think I am leaning towards a blanket note on old post stating that some old links may not work, etc. I'd rather not retroactively edit old blog entries as new website content wouldn't match up. :)

**Comment by edk0** [comment]
Dealt with in #225
