### ISSUE TITLE
Design: Font leads to slight horizontal misalignment

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#188]
The font used leads to slight (1-2 pixel) horizontal misalignment. 
This is best seen in titles, e.g.

[![screenshot of the issue](http://imgur.com/Eu8OPFn.png)](http://imgur.com/Eu8OPFn)

 but also happens in normal paragraphs. 

Affected letters seem to be at least N, R and H, which are slightly shifted to the right. 

As this seems to be a font issue that can't be fixed easily, maybe consider a different font.

(Sounds like a minor issue, I fully agree, however, it's one of these things that bother you a lot, even without having OCD or the likes. There is something slightly wrong, and you at first can't figure out what)

**Comment by edk0** [comment]
I'm closing this because although I completely agree with you I don't think there is a practical solution
