### ISSUE TITLE
Knowledge Base Permalinks Hard to Find

### ISSUE THREAD

**Issue by nhandler** [freenode/web-7.0#199]
Now that we don't have a Table of Contents, the only way to determine the proper way to link to a heading in the Knowledge Base is to examine the source and find the proper id. Could we maybe add some anchor icons after each heading to make this easier?

**Comment by svbeon** [comment]
Well the goal is to split the content across different pages instead of using anchors, so no, probably not

**Comment by christeld** [comment]
@nhandler soz. Entirely deliberate!
