### ISSUE TITLE
Knowledge Base Permalinks Hide Heading

### ISSUE THREAD

**Issue by nhandler** [freenode/web-7.0#200]
If I attempt to go to a URL such as http://freenode.net/kb/answer/registration#nickname-setup , the page scrolls to the correct section, but the section header gets hidden behind the top black navbar. This makes it impossible to read.

**Comment by svbeon** [comment]
Well, you can indeed scroll. And as said, the anchors aren't even ment to be there...

**Comment by mistohise** [comment]
Why would people be visiting  http://freenode.net/kb/answer/registration#nickname-setup on such a short page?

**Comment by edk0** [comment]
We do need to commit to making sure pages are sufficiently short, and I should probably get the software to stop generating anchors; I'll think about how to split this into other issues.
