### ISSUE TITLE
Clearly note when data is being shared with a third party (i.e. Google)

### ISSUE THREAD

**Issue by nhandler** [freenode/web-7.0#201]
I received a request from a user who wishes to remain anonymous.

They would like the search box in the upper right corner of the site to clearly note that it is a "Google Custom Search". This would allow them to opt-out of sharing their search details with Google for privacy reasons. Ideally, they would also like a privacy policy that covers the use of Google Analytics and such.

**Comment by Fuchs** [comment]
That is why I suggested using startpage / ixquick in #freenode-web, including a snippet how to do so. However, within the discussion it was made clear that google in the past was okay and apparently there aren't too many concerns about it user side, and I personally don't care too much about it either. 

If, however, this comes up more frequently: that would be a valid alternative  (it uses google internally, it just acts as a proxy) and a portal I worked with uses it successfully

I agree on google analytics and the likes  (actually I recommended using an own piwik instance instead, but as freenode prefers to not host things themselves any more I don't think that's a solution).

**Comment by svbeon** [comment]
Maybe just throw privacy.md into pages where we state:
  - * use of ga
  - * ga's use of cookies
  - * use of cse

**Comment by mistohise** [comment]
Why?

**Comment by edk0** [comment]
We could probably kill freenode/www#1 with the same stone.

**Comment by svbeon** [comment]
@mistohise Europe's cookie policy, GDPR... Mostly law related.

**Comment by Agrivane** [comment]
If a person wants to avoid sending information to a specific agency online, they must configure their system to drop/null route/ignore that agency's assets or use a filtering proxy which does the same.

**Comment by edk0** [comment]
I think it's relatively fair to assume that their data isn't being sent to Google unless they ask for it to be. "Everyone owns your data unless you hide from them" isn't a great way to run the internet.

**Comment by emersonveenstra** [comment]
Would something like this be a good idea until we can get a privacy policy?
![cse](https://cloud.githubusercontent.com/assets/5402360/16346525/c38ebe76-3a15-11e6-875f-2df538fb8a01.png)
![cse-mobile](https://cloud.githubusercontent.com/assets/5402360/16346524/c38cd53e-3a15-11e6-8afe-3e71149f5b17.png)

**Comment by Fuchs** [comment]
I think that's a great idea with or without a privacy policy, yes :+1:

**Comment by svbeon** [comment]
We removed the Google analytics, can we close this?
