### ISSUE TITLE
Links in Chanserv are broken

### ISSUE THREAD

**Issue by DoctorD90** [freenode/web-7.0#202]
Links to the site are not valid. Site has changed, but links in the services are not be updated.
Ex. /msg ChanServ register #test
...
-ChanServ- (http://freenode.net/channel_guidelines.shtml).
...
-ChanServ- http://freenode.net/policy.shtml#primarychannels

I havent checked in other services.

**Comment by svbeon** [comment]
I notified @staff a while ago... Tough this is not an issue with the website, but with services. Thus I'll close this issue
