### ISSUE TITLE
Hidden characters in service nicks causes errors when copying into IRC

### ISSUE THREAD

**Issue by prawnsalad** [freenode/web-7.0#211]
Copy/pasting commands from the website (eg. https://freenode.net/kb/answer/registration) fails when using within IRC due to hidden characters in the nick. `&shy;` is used in the middle of `NickServ`

**Comment by edk0** [comment]
Ack. We should probably make `<code>` and/or `<pre>` immune to hyphenation.

**Comment by aprekates** [comment]
Trying to set a new server in a new irssi installation with copy pasting i've lost two hours trying
to figure out what wrong with irssi. 
Please correct that. i think it's common use case scenario to copy paste.

Also please explain what happened to the old servers list page. 
New website is cool but lacks some much needed info .

**Comment by edk0** [comment]
Removing the server list was quite deliberate, and it won't be coming back.

The soft hyphens inside `<code>` and `<pre>` elements will be going away momentarily, on the other hand :).

**Comment by emersonveenstra** [comment]
This doesn't fix soft hyphens in the rest of the pages though, i.e. http://freenode.net/changuide is full of them. 

Is there a reason why soft hyphen characters are needed rather than letting the browser handle hyphenation/wrapping?

**Comment by edk0** [comment]
> Is there a reason why soft hyphen characters are needed rather than letting the browser handle hyphenation/wrapping?

Yeah—because they don't handle it :(
