### ISSUE TITLE
Change license to CC BY-SA 4.0 International

### ISSUE THREAD

**Issue by Calinou** [freenode/web-7.0#224]
Currently, the site is using CC BY-NC-SA 4.0.

What about switching to CC BY-SA 4.0, which is effectively a free culture license? (I could have made a pull request, but didn't find the CC BY-SA version of the SVG badge that's currently used on the site.)

[More information.](http://freedomdefined.org/Licenses/NC)

**Comment by svbeon** [comment]
Okay, first off:
  - One does not simply switch licence
The reasons are simple: we have 19 contributors, to relicense every single one of them has to agree to it and some of those are hard to reach.

The content in this repo is mainly editorial work that their authors want protected. By using by-nc-sa we guarantee that the editorial content can be freely redistributed as long as the content doesn't play a main role in generating profit for the redistributer, profit that can place freenode in a context they don't want to be seen in.

The other content is design work (css and templates) where the only way to directly profit on it is selling it or any of its derivatives which once again can put us in a context we don't want to be in. We want our style work to be free of charge and by-nc-sa is a way for us to guarantee that

**Comment by svbeon** [comment]
[link to creative commons download page with svg icons](https://creativecommons.org/about/downloads/)

**Comment by nemobis** [comment]
This may not be simple, but it will only get harder over time. Using a nonfree license doesn't reflect well on a project which supports free software projects.
https://meta.wikimedia.org/wiki/Free_knowledge_based_on_Creative_Commons_licenses
https://freedomdefined.org/Licenses/NC

**Comment by swantzter** [comment]
@nemobis I appreciate your thoughts here, but unfortunately by this point is simply isn't possible without essentially reworking the entire site and all content - the other option would be to contact all copyright holders (all 47) and gain consensus. Several of which we have no way of contacting as they may have left their connections to IRC and freenode behind.

I can't speak to why NC was chosen five years ago, but at this point changing is simply not feasible.
