### ISSUE TITLE
The certfp docs are gone

### ISSUE THREAD

**Issue by dequis** [freenode/web-7.0#242]
And the cloudflare 404 page helpfully suggests checking out the following URLs which are 404'd too.

```
Identifying with CERTFP
http://freenode.net/certfp/

Configuring Client SSL Certificates for ChatZilla
http://freenode.net/certfp/certfp-chatzilla.shtml

Configuring Client SSL Certificates for mirc
http://freenode.net/certfp/certfp-mirc.shtml

Configuring Client SSL Certificates for Quassel
http://freenode.net/certfp/certfp-quassel.shtml
```

**Comment by Mikaela** [comment]
Would it be possible to clear the CloudFlare 404 page suggestions and get it to reindex so it would only show existing links?

**Comment by edk0** [comment]
Good question. I'll bother some infra people about it.
