### ISSUE TITLE
add newsletter feature

### ISSUE THREAD

**Issue by SvetlanaTkachenko** [freenode/web-7.0#253]
random idea: put wallop contents onto the blog, and put everything from the blog into a newsletter
so people can subscribe to it using their email

the web site is static, so I'm not sure how to implement this ( many web sites have a newsletter subscribe offer in sidebar with a text box for typing the address )

**Comment by svbeon** [comment]
Well technically, if you want to subscribe you could potentially just use
the rss feeds: [news/rss.xml](https://freenode.net/news/rss.xml) or
[news/atom.xml](https://freenode.net/news/atom.xml)

Google does have a site for turning xml feeds into newsletters called
[feedburner](http://feedburner.google.com) so it's quite easy to make a
personal one...

Den fre 9 sep. 2016 15:57Svetlana Tkachenko <notifications@github.com>
skrev:

**Comment by emersonveenstra** [comment]
> random idea: put wallop contents onto the blog

This isn't a great idea, wallops are generally shortened to fit into an IRC message, and if it's worthy of being a blog post, we'll make it one and then wallop the blog link

> and put everything from the blog into a newsletter
> so people can subscribe to it using their email
> 
> the web site is static, so I'm not sure how to implement this ( many web sites have a newsletter subscribe offer in sidebar with a text box for typing the address )

Correct, the site being static means that there's no way for us to easily send out a newsletter, people can subscribe to the RSS feed as mentioned above
