### ISSUE TITLE
Add password reset instructions to KB

### ISSUE THREAD

**Issue by berezovskyi** [freenode/web-7.0#254]
The most relevant page on account operations is https://freenode.net/kb/answer/registration.

There is no information on the page on how to reset the password of an existing account. I got it from #freenode channel:

```
/msg nickserv SENDPASS <nickname>
```

I now understand it's a basic and well-known command, but I think it will be useful for the KB.

**Comment by equinox** [comment]
Added in https://github.com/freenode/web-7.0/pull/293.
