### ISSUE TITLE
Issue with the page "General Expectations for Conduct"

### ISSUE THREAD

**Issue by jcjordyn130** [freenode/web-7.0#282]
On that last bullet point where it says "beliefs", it would be better to be a little less vague about it. Like what kind of beliefs: political or religious?.

**Comment by svbeon** [comment]
Both and others.

That one is left vauge intentionally, we mean all beliefs, political, religious, philosophical, psychological, structural, economical etc.

**Comment by mistohise** [comment]
We are looking at re-wording this section.

**Comment by mistohise** [comment]
Hopefully the replacement for this is more appropriate.

**Comment by jcjordyn130** [comment]
I hope so too. :)
