### ISSUE TITLE
The site renders differently in different browsers

### ISSUE THREAD

**Issue by mistohise** [freenode/web-7.0#294]
Looking at the site e.g. http://freenode.net/kb/all in Chrome, Edge and IE 11 gives very different visual results. 
Chrome displays the header and footer with a dark background, the others have white backgrounds. In IE 11, the freenode logo only shows the top left corner "freen" and the PIA logo does not appear correctly. In Edge, the freenode logo appears but PIA does not appear properly. 

In IE, the CC logo at the bottom is cut off. 

Lastly, in both IE and Edge, the KB category links fill the entire page, whereas in Chrome they appear centered and width limited.

**Comment by mistohise** [comment]
![freenodechrome](https://cloud.githubusercontent.com/assets/9051085/23266121/b2a651ee-f9de-11e6-9232-3730a2eb4cb3.jpg)
![freenodeie11](https://cloud.githubusercontent.com/assets/9051085/23266123/b2aa911e-f9de-11e6-97c0-372e33fdaa98.jpg)
![freenodeedge](https://cloud.githubusercontent.com/assets/9051085/23266122/b2a8e10c-f9de-11e6-8439-11ce1edc36e4.jpg)

**Comment by svbeon** [comment]
yes, the build script and css preprocessing is currently broken, we're on it

**Comment by svbeon** [comment]
Solved with <3481522d>
