### ISSUE TITLE
Provide a privacy policy

### ISSUE THREAD

**Issue by yoru** [freenode/web-7.0#311]
It seems awful that freenode doesn't have a privacy policy. It's supposed to be easy to find, yet I couldn't find it after browsing the website for a while.

**Comment by svbeon** [comment]
see freenode/www#15 and #201

**Comment by mitki** [comment]
Thank you @svbeon.
Yet, I think it's still useful (and reassuring for the users) to implement a privacy policy on the website footer, since the last issue is dated from 2015.

**Comment by svbeon** [comment]
yes, we'll look into it, however that old privacy policy is still effective as far as i'm concerned. but better check with @christeld

**Comment by christeld** [comment]
policies.md updated to re-introduce brief privacy policy and retention information.
