### ISSUE TITLE
https://www.freenode.net redirects to http://freenode.net

### ISSUE THREAD

**Issue by Zarthus** [freenode/web-7.0#340]
The www. url is used in the MOTD of (some/all) servers, so the redirect is just silly and a downgrade.

**Comment by mquin** [comment]
Fixed MOTD.

**Comment by Zarthus** [comment]
You don't think the redirect is an issue?

**Comment by mquin** [comment]
The canonical version of the name is freenode.net, the www redirect is just for convenience as some older links will point to it and many users may type it anyway.

As I understand it serving the same content under different names without a redirect can cause issues with search engine rankings and the like.

**Comment by Zarthus** [comment]
A redirect to https://freenode.net would probably still be better than to http;// by itself, but I agree that next to nobody will be linking to www.*

**Comment by svbeon** [comment]
See #144 and #178
