### ISSUE TITLE
Incorrect password when logging to IRC

### ISSUE THREAD

**Issue by einsteinsfool** [freenode/web-7.0#381]
When I go to https://webchat.freenode.net and try to log in to my IRC account, after connecting I see this message:
```
[18:58] -NickServ- This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
[18:58] -NickServ- Invalid password for einsteinsfool.
```
When I then use this command: `/msg NickServ identify that_same_copy_pasted_password` I can successfully log in.

I'll add that my password is over 100 characters long and contains all kinds of special characters, like tilde and grave accent. If necessary, I can change my password and provide the old one in full for you to debug.

I assumed it's Freenode's bug since it happens during logging to IRC. If it's qwebirc's bug, let me know and I'll post this issue on their GitHub.

**Comment by svbeon** [comment]
Closing as this is not an issue with https://freenode.net (this reop with our blog, knowledge base etc) but with qwebirc or our fork of qwebirc. We are currently looking on making updates to the webchat that we hope will solve this.
