### ISSUE TITLE
pls drop the name powerolive to me

### ISSUE THREAD

**Issue by PowerOlive** [freenode/web-7.0#383]
i wanna register it but i input a wrong email and password as a test
i donot wanna it come true help help

**Comment by svbeon** [comment]
Hi, this has nothing to do with the freenode.net website, which this repo is for. However you could ask a member of staff while connected for help on this. To see staff that are currently available you can send the command `/stats p`

**Comment by PowerOlive** [comment]
thanks

**Comment by PowerOlive** [comment]
you seem in utc+8 too:)
