### ISSUE TITLE
Link no longer exist

### ISSUE THREAD

**Issue by YourNeighbour** [freenode/web-7.0#387]
Hello there. I try to register my nickname in freenode irc server but link that placed on unity wiki website is no longer exist. [http://freenode.net/faq.shtml#nicksetup](url)

How can I register my nickname. Thanx

**Comment by svbeon** [comment]
On the 404 page you arrive at there should be a link to [registering your nick](https://freenode.net/kb/answer/registration)

You should open an issue with Unity and ask them to update their links
