### ISSUE TITLE
document tor configuration with MapAddress

### ISSUE THREAD

**Issue by xnrand** [freenode/web-7.0#413]
https://github.com/freenode/web-7.0/blob/cb21983f058ce11718176ec60a5974c1a2b13462/content/kb/connect/chat.md#L73-L77

In the documentation on how to connect over tor, the reader is told to disable verification in their client if it doesn't support _key_ pinning.

There is a better option when using tor: By using the `MapAddress` configuration directive, tor can be instructed to redirect requests for one address (such as `zettel.freenode.net`) to another one (such as the freenode hidden service). That way, a client still thinks it's connecting to `zettel.freenode.net`, so that the certificate validates properly and is considered trusted.

```
# torrc snippet:
MapAddress zettel.freenode.net ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion
```

In my opinion, the documentation should be updated to reflect this alternative

**Comment by Mikaela** [comment]
Reading the torrc manual, I think the entry should be

`MapAddress *.freenode.net ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion`

because it supports wildcards and MapAddress only affects Tor connections and I think freenode is blocking all Tor connections outside of the Onion service?

```
       MapAddress address newaddress
           When a request for address arrives to Tor, it will transform to newaddress before processing it. For example, if you always want
           connections to www.example.com to exit via torserver (where torserver is the fingerprint of the server), use "MapAddress
           www.example.com www.example.com.torserver.exit". If the value is prefixed with a "*.", matches an entire domain. For example, if
           you always want connections to example.com and any if its subdomains to exit via torserver (where torserver is the fingerprint of
           the server), use "MapAddress *.example.com *.example.com.torserver.exit". (Note the leading "*." in each part of the directive.)
           You can also redirect all subdomains of a domain to a single address. For example, "MapAddress *.example.com www.example.com".

           NOTES:

            1. When evaluating MapAddress expressions Tor stops when it hits the most recently added expression that matches the requested
               address. So if you have the following in your torrc, www.torproject.org will map to 1.1.1.1:

                   MapAddress www.torproject.org 2.2.2.2
                   MapAddress www.torproject.org 1.1.1.1

            2. Tor evaluates the MapAddress configuration until it finds no matches. So if you have the following in your torrc,
               www.torproject.org will map to 2.2.2.2:

                   MapAddress 1.1.1.1 2.2.2.2
                   MapAddress www.torproject.org 1.1.1.1

            3. The following MapAddress expression is invalid (and will be ignored) because you cannot map from a specific address to a
               wildcard address:

                   MapAddress www.torproject.org *.torproject.org.torserver.exit

            4. Using a wildcard to match only part of a string (as in *ample.com) is also invalid.
```

**Comment by emersonveenstra** [comment]
That wouldn't help the certificate verification, because if you used `orwell.freenode.net`, the certificate wouldn't verify because it's only valid for zettel and the round robin DNS names.

However, using chat.freenode.net instead of zettel.freenode.net should work too, although I haven't tested it

**Comment by christeld** [comment]
Fixed in https://github.com/freenode/web-7.0/pull/432
