### ISSUE TITLE
Document umode/cmode +u

### ISSUE THREAD

**Issue by svbeon** [freenode/web-7.0#422]
`+u` was recently introduced as mentioned in the blog post about [ircd-seven 1.1.8](https://freenode.net/news/seven-118) which opts a channel or user out of the server-side spam filtering. this should probably be reflected in [content/kb/using/channelmodes.md](/freenode/web-7.0/blob/master/content/kb/using/channelmodes.md) and [content/kb/using/usermodes.md](/freenode/web-7.0/blob/master/content/kb/using/usermodes.md)

**Comment by RhinosF1** [comment]
Done

**Comment by svbeon** [comment]
fixed by #426
