### ISSUE TITLE
Suggest using a unique password for nickserv registration.

### ISSUE THREAD

**Issue by RealKindOne** [freenode/web-7.0#435]
https://freenode.net/kb/answer/registration

Change:
>Replace "YourPassword" with a secure, unguessable password that you keep secret.

Into something like: 
>Replace "YourPassword" with a secure, unguessable password that you keep secret. Please do not reuse any passwords you use elsewhere.

Password reuse is a Bad Idea™

https://freenode.net/news/security-update-rpa

**Comment by RhinosF1** [comment]
Is that good @RealKindOne ?
