### ISSUE TITLE
Repo branches spring cleanup?

### ISSUE THREAD

**Issue by svbeon** [freenode/web-7.0#439]
With the recent pr #434 it might be worth also looking through the 20 branches we have on this repo and remove those that have already been merged, and those that have been abandoned

**Comment by bigpresh** [comment]
OOI - why?  What harm does historical branches being around cause?

**Comment by svbeon** [comment]
@bigpresh why not? I mean I don't really feel any big push to do this, that's why I wrote it as a question. I'm personally thinking it might make it a little easier to overview things but that might just be how I'm wired
