### ISSUE TITLE
Use a private alternative to Google's reCaptcha

### ISSUE THREAD

**Issue by 12people** [freenode/web-7.0#441]
As it stands, Google's reCaptcha [partly relies on tracking users' online behavior](https://www.fastcompany.com/90369697/googles-new-recaptcha-has-a-dark-side) to decide whether a person is a robot or not.

Right now, reCaptcha is used in freenode's web interface. I'd much rather a privacy-minded alternative be used. [hCaptcha](https://hcaptcha.com/) is probably the best-known privacy-oriented alternative, though I'm sure there are others.

**Comment by svbeon** [comment]
Hey, thanks for suggesting a seemingly great alternative! However, could I ask you to open this issue on [freenode/kiwiirc](https://github.com/freenode/kiwiirc) instead? That's the webchat and the only place we use reCaptcha

**Comment by 12people** [comment]
@svbeon Just created it: https://github.com/freenode/kiwiirc/issues/22

Thanks for pointing me in the right direction! :)
