### ISSUE TITLE
Mixed use of terms SSL and TLS

### ISSUE THREAD

**Issue by mquin** [freenode/web-7.0#443]
Various documents on the site use the terms SSL and TLS to refer to TLS, sometimes both in the same document.

**Comment by jesopo** [comment]
would a better solution be to use "TLS" everywhere? except in client documentation, for commands that need e.g. `--ssl`

or are there some circumstances under which the wider understanding of "SSL" over "TLS" would deem something like "SSL/TLS" useful?

**Comment by swantzter** [comment]
I think we should go with TLS consistently (except in flags like you mention @jesopo) after all that's the name of what is being used and the term that should replace SSL

**Comment by glguy** [comment]
I made a PR that I think is a great step forward. If it turns out we want a different change I won't be offended, but at least we have something ready to go now.
