### ISSUE TITLE
#postfix freenode IRC welcome instructions point to old registering FAQ link

### ISSUE THREAD

**Issue by prep-gh** [freenode/web-7.0#446]
#postfix freenode IRC welcome instructions point to old registering FAQ link.

*So new users do not know how to register*.

http://freenode.net/faq.shtml#registering

"-ChanServ- [#postfix] Glad to have you on #postfix. Unfortunately because of attacks on Freenode IRC, we have had to limit participation to  registered users. Please see http://freenode.net/faq.shtml#registering if you are not registered. For questions in the channel, please read our  /topic and type "!welcome" -- the bot will answer you."

**Comment by svbeon** [comment]
This is something you'll have to bring up with postfix - it's not an issue with the freenode website. Postfix will have to update their chanserv enteymsg
