### ISSUE TITLE
cloudsigma link has &amp; wrongly

### ISSUE THREAD

**Issue by jesopo** [freenode/web-7.0#485]
`https://www.cloudsigma.com/?utm_source=freenode&amp;utm_medium=banner&amp;utm_campaign=sponsoring`

should be

`https://www.cloudsigma.com/?utm_source=freenode&utm_medium=banner&utm_campaign=sponsoring`

**Comment by swantzter** [comment]
To the tune of "do you wanna build a snowman": "do you wanna make a pull request?"

**Comment by gcbirzan** [comment]
I don't, but I will tomorrow when I get to work. 

But, I mean, we could just withdraw the sponsorship, if this request is inconveniencing you so much...

**Comment by jesopo** [comment]
I think Swant was asking  if *I* wanted to, which I did intend to when I made this issue,  but  the weekend overtook me  :)

**Comment by gcbirzan** [comment]
As I told you, you should've just pointed me to this repo. Don't worry, I'll take care of it tomorrow morning EU time.
