### ISSUE TITLE
Use directly on web hosting

### ISSUE THREAD

**Issue by gusmanp** [freenode/web-7.0#488]
Sorry for my question if it's wrong
I want to try installing the theme of this website
but I immediately downloaded the .zip file and immediately uploaded it to my hosting (I don't have a vps)
can that be?
but I have tried and opened the home page but it only looks like a folder, the problem is there is no index.html file.
please help and solution, thanks

**Comment by bigpresh** [comment]
The README tells you how its designed to be deployed etc - just uploading a ZIP file of it to a shared hosting account isn't going to do it.

What are you trying to achieve?

Why do you want to use the freenode website on your hosting?

**Comment by swantzter** [comment]
Hi, you need to build the repository using cms7. You can find detailed instructions on how in the [README.md](https://github.com/freenode/web-7.0/blob/main/README.md) file.

After that you'll want to deploy the `out/` directory to a server.

Keep in mind that this repository isn't exactly a theme but rather a full website with specialised build tools that are meant to handle a very specific way of structuring this particular website to cater to our particular use case. You most likely don't want to use this repo without major changes to suit your particular needs.

**Comment by swantzter** [comment]
(I marked this as invalid and closed it since its not an issue with the project itself, but rather a question about it. Feel free to continue the conversation nevertheless)
