### ISSUE TITLE
Get fucked.

### ISSUE THREAD

**Issue by Joshua-Ashton** [freenode/web-7.0#523]
Hi Andrew,

How does it feel that the entire open source community hates you?

You know, you really live up to your "royal" title.
You act like a spoilt child and a dictator and have ruined any form of trust or respect anyone had by your temper tantrums of this hostile take over, taking over channels, and hiring open racists and homophobes as your new staff members.

You babble on about "cancel culture" as if it's anything about your political beliefs, and not that people are just reacting to how much of a power-hungry dipshit you really are and how you have severely violated their trust.

The open source community does not want or need you.

Anyway, everywhere I frequent has moved, just writing here to leave my final message.

@realrasengan, fuck you.

**Comment by senposage** [comment]
agree get fucked
