### ISSUE TITLE
Get fucked.

### ISSUE THREAD

**Issue by Joshua-Ashton** [freenode/web-7.0#524]
Hi Andrew,

How does it feel that the entire open source community hates you?

You know, you really live up to your "royal" title.
You act like a spoilt child and a dictator and have ruined any form of trust or respect anyone had by your temper tantrums of this hostile take over, taking over channels, and hiring open racists and homophobes as your new staff members.

You babble on about "cancel culture" as if it's anything about your political beliefs, and not that people are just reacting to how much of a power-hungry dipshit you really are and how you have severely violated their trust.

The open source community does not want or need you.

Anyway, everywhere I frequent has moved, just writing here to leave my final message.

@realrasengan, fuck you.

Previous issue at https://github.com/freenode/web-7.0/issues/523 was closed, so I guess I have another person to reference:

@trobotham, fuck you.

**Comment by waltercool** [comment]
Can someone just ban this troll?

**Comment by Joshua-Ashton** [comment]
Yes, I am the troll. Not the asshole doing the hostile take over of the largest IRC network. Imagine being this fucking delusional.

**Comment by simoniz0r** [comment]
One man singlehandedly killed the most popular IRC network on the planet.  What a fuckhead.
