### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by svbeon** [freenode/web-7.0#57]
All images must be downloaded from old blog and correctly linked in news

**Comment by svbeon** [comment]
I'll just rerun https://github.com/thomasf/exitwp/ with download images on in config. I'll fix it later today

**Comment by mission712** [comment]
Suit yourself. ^.^12

**Comment by svbeon** [comment]
Sadly it appears the images that gets downloaded are broken

**Comment by svbeon** [comment]
Done
