### ISSUE TITLE
Palette

### ISSUE THREAD

**Issue by edk0** [freenode/web-7.0#64]
We're using a lot of slightly different colours:

```
;; grep -o '#......' static/css/style.css|tr A-Z a-z|sort|uniq
#292f2f
#2fa6bc
#3a4346
#4beb4a
#4c5456
#bdbcbc
#e6e6e6
#ecf7fa
```

We probably want to do something about that.

**Comment by mission712** [comment]
1, 6 and 7 are most likely staying. I don't know about the others, though.

**Comment by svbeon** [comment]
I'm trying an approach with color()

**Comment by svbeon** [comment]
Giving up on that approach
