### ISSUE TITLE
Feed generator

### ISSUE THREAD

**Issue by edk0** [freenode/web-7.0#93]

**Comment by edk0** [comment]
Should also be podcast-capable

**Comment by svbeon** [comment]
Podcast - yes - from christel

**Comment by PriceChild** [comment]
For bonus points, place it under /feed/ so that our old syndications to http://blog.freenode.net/feed/ continue to work.

**Comment by svbeon** [comment]
Implemented, should close?

**Comment by edk0** [comment]
yee
